suspend
setdirection player 7
if flag angry_woman_gone
if flag spoken_to_receptionist_once
playdialog ReceptionistStandard 700 120 400 80
else
playdialog ReceptionistFirstTime 700 120 400 80
playdialog ReceptionistStandard 700 120 400 80
raiseflag spoken_to_receptionist_once
endif
else
setdirection player 4
showtext 250 250 5 30 I 255 0 255 17 I can't talk to the receptionist as she is in a loud conversation with the angry lady.
endif
resume